package com.talentboard.enums;

public enum Categories {
    SOFTWARE_ENGINEERING,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    CYBERSECURITY,
    CLOUD_COMPUTING,
    DEVOPS,
    FRONTEND_DEVELOPMENT,
    BACKEND_DEVELOPMENT,
    FULL_STACK_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GAME_DEVELOPMENT,
    QA_TESTING,
    DATABASE_ADMINISTRATION,
    SYSTEMS_ADMINISTRATION,

    PRODUCT_MANAGEMENT,
    PROJECT_MANAGEMENT,
    BUSINESS_ANALYSIS,
    OPERATIONS_MANAGEMENT,
    SUPPLY_CHAIN_MANAGEMENT,

    MARKETING,
    DIGITAL_MARKETING,
    CONTENT_CREATION,
    SEO_SPECIALIST,
    SOCIAL_MEDIA_MANAGEMENT,
    BRAND_MANAGEMENT,
    PUBLIC_RELATIONS,

    SALES,
    ACCOUNT_MANAGEMENT,
    CUSTOMER_SUCCESS,
    BUSINESS_DEVELOPMENT,
    RETAIL,

    HUMAN_RESOURCES,
    TALENT_ACQUISITION,
    ORGANIZATIONAL_DEVELOPMENT,
    PAYROLL,

    FINANCE,
    ACCOUNTING,
    AUDITING,
    INVESTMENT_BANKING,
    FINANCIAL_ANALYSIS,

    LEGAL,
    COMPLIANCE,
    RISK_MANAGEMENT,

    HEALTHCARE,
    NURSING,
    MEDICAL_DOCTOR,
    PHARMACY,
    BIOTECHNOLOGY,

    EDUCATION,
    TEACHING,
    RESEARCH,
    ACADEMIC_ADMINISTRATION
}
